"""Seed data for the mock customer directory API.

Deliberately small and hand-written so answers are easy to verify by eye when
checking what the agent reports back.

Addresses are held apart from the core customer record and served by their own
endpoints, so that access to a customer's home address can be authorized
separately from their work address and the rest of the record.
"""

CUSTOMERS = [
    {
        "id": "C-1001",
        "name": "Dana Whitfield",
        "email": "dana.whitfield@northharbor.example.com",
        "phone": "+1-617-555-0142",
        "company": "North Harbor Logistics",
        "job_title": "Director of Operations",
        "status": "active",
        "customer_since": "2019-03-11",
        "account_tier": "enterprise",
        "work_address": {
            "street": "200 Seaport Boulevard, Suite 1400",
            "city": "Boston",
            "state": "MA",
            "postal_code": "02210",
        },
        "home_address": {
            "street": "418 Harrowgate Lane",
            "city": "Newton",
            "state": "MA",
            "postal_code": "02458",
        },
    },
    {
        "id": "C-1002",
        "name": "Marcus Bell",
        "email": "marcus.bell@lonestardata.example.com",
        "phone": "+1-512-555-0119",
        "company": "Lone Star Data Works",
        "job_title": "Chief Technology Officer",
        "status": "active",
        "customer_since": "2021-07-06",
        "account_tier": "enterprise",
        "work_address": {
            "street": "901 East 6th Street, Floor 3",
            "city": "Austin",
            "state": "TX",
            "postal_code": "78702",
        },
        "home_address": {
            "street": "2207 Cedar Bend Drive",
            "city": "Austin",
            "state": "TX",
            "postal_code": "78745",
        },
    },
    {
        "id": "C-1003",
        "name": "Priya Raghunathan",
        "email": "priya.raghunathan@cascadeanalytics.example.com",
        "phone": "+1-503-555-0177",
        "company": "Cascade Analytics",
        "job_title": "VP Engineering",
        "status": "active",
        "customer_since": "2022-01-24",
        "account_tier": "growth",
        "work_address": {
            "street": "1120 Southwest Morrison Street, Suite 800",
            "city": "Portland",
            "state": "OR",
            "postal_code": "97205",
        },
        "home_address": {
            "street": "91 Alder Court, Apt 4B",
            "city": "Portland",
            "state": "OR",
            "postal_code": "97214",
        },
    },
    {
        "id": "C-1004",
        "name": "Tomas Lindqvist",
        "email": "tomas.lindqvist@quincymill.example.com",
        "phone": "+1-617-555-0163",
        "company": "Quincy Mill Supply",
        "job_title": "Controller",
        "status": "active",
        "customer_since": "2020-09-14",
        "account_tier": "standard",
        "work_address": {
            "street": "45 Hancock Street",
            "city": "Quincy",
            "state": "MA",
            "postal_code": "02169",
        },
        "home_address": {
            "street": "77 Sagamore Street",
            "city": "Quincy",
            "state": "MA",
            "postal_code": "02171",
        },
    },
    {
        "id": "C-1005",
        "name": "Aisha Nakamura",
        "email": "aisha.nakamura@lakeshorehealth.example.com",
        "phone": "+1-312-555-0158",
        "company": "Lakeshore Health Partners",
        "job_title": "Head of People",
        "status": "active",
        "customer_since": "2018-05-02",
        "account_tier": "enterprise",
        "work_address": {
            "street": "233 North Michigan Avenue, Suite 2100",
            "city": "Chicago",
            "state": "IL",
            "postal_code": "60601",
        },
        "home_address": {
            "street": "1540 West Berteau Avenue",
            "city": "Chicago",
            "state": "IL",
            "postal_code": "60613",
        },
    },
    {
        "id": "C-1006",
        "name": "Gregory Osei",
        "email": "gregory.osei@peachtreeretail.example.com",
        "phone": "+1-404-555-0190",
        "company": "Peachtree Retail Group",
        "job_title": "Regional Director",
        "status": "active",
        "customer_since": "2017-11-20",
        "account_tier": "growth",
        "work_address": {
            "street": "3630 Peachtree Road NE, Suite 900",
            "city": "Atlanta",
            "state": "GA",
            "postal_code": "30326",
        },
        "home_address": {
            "street": "3325 Peachtree Hollow",
            "city": "Atlanta",
            "state": "GA",
            "postal_code": "30319",
        },
    },
    {
        "id": "C-1007",
        "name": "Helena Vargas",
        "email": "helena.vargas@frontrangesec.example.com",
        "phone": "+1-303-555-0134",
        "company": "Front Range Security",
        "job_title": "Principal Consultant",
        "status": "active",
        "customer_since": "2023-02-13",
        "account_tier": "standard",
        "work_address": {
            "street": "1550 Wewatta Street, Floor 2",
            "city": "Denver",
            "state": "CO",
            "postal_code": "80202",
        },
        "home_address": {
            "street": "612 Ridgecrest Terrace",
            "city": "Denver",
            "state": "CO",
            "postal_code": "80206",
        },
    },
    {
        "id": "C-1008",
        "name": "Robert Chen",
        "email": "robert.chen@vinings-partners.example.com",
        "phone": "+1-770-555-0126",
        "company": "Vinings Partners",
        "job_title": "Managing Partner",
        "status": "churned",
        "customer_since": "2021-04-19",
        "closed_on": "2026-06-30",
        "account_tier": "standard",
        "work_address": {
            "street": "2870 Paces Ferry Road, Suite 300",
            "city": "Atlanta",
            "state": "GA",
            "postal_code": "30339",
        },
        "home_address": {
            "street": "884 Vinings Ridge Road",
            "city": "Smyrna",
            "state": "GA",
            "postal_code": "30080",
        },
    },
    {
        "id": "C-1009",
        "name": "Yuki Tanaka",
        "email": "yuki.tanaka@charlesriverfin.example.com",
        "phone": "+1-617-555-0181",
        "company": "Charles River Financial",
        "job_title": "Senior Analyst",
        "status": "prospect",
        "customer_since": "2026-08-07",
        "account_tier": "standard",
        "work_address": {
            "street": "1 Broadway, Floor 14",
            "city": "Cambridge",
            "state": "MA",
            "postal_code": "02142",
        },
        "home_address": {
            "street": "23 Bowdoin Street, Unit 2",
            "city": "Cambridge",
            "state": "MA",
            "postal_code": "02138",
        },
    },
    {
        "id": "C-1010",
        "name": "Sandra Okonkwo",
        "email": "sandra.okonkwo@beaconhillcap.example.com",
        "phone": "+1-617-555-0107",
        "company": "Beacon Hill Capital",
        "job_title": "Chief Financial Officer",
        "status": "active",
        "customer_since": "2015-01-12",
        "account_tier": "enterprise",
        "work_address": {
            "street": "84 State Street, Suite 600",
            "city": "Boston",
            "state": "MA",
            "postal_code": "02109",
        },
        "home_address": {
            "street": "5 Louisburg Square",
            "city": "Boston",
            "state": "MA",
            "postal_code": "02108",
        },
    },
    {
        "id": "C-1011",
        "name": "Daniel Ferreira",
        "email": "daniel.ferreira@shoalcreektech.example.com",
        "phone": "+1-512-555-0148",
        "company": "Shoal Creek Technologies",
        "job_title": "Founder",
        "status": "active",
        "customer_since": "2016-06-27",
        "account_tier": "growth",
        "work_address": {
            "street": "1109 Shoal Creek Boulevard, Suite 200",
            "city": "Austin",
            "state": "TX",
            "postal_code": "78701",
        },
        "home_address": {
            "street": "4402 Balcones Drive",
            "city": "Austin",
            "state": "TX",
            "postal_code": "78731",
        },
    },
    {
        "id": "C-1012",
        "name": "Meredith Cole",
        "email": "meredith.cole@hoyneandco.example.com",
        "phone": "+1-312-555-0172",
        "company": "Hoyne & Company",
        "job_title": "Principal",
        "status": "inactive",
        "customer_since": "2017-02-06",
        "account_tier": "standard",
        "work_address": {
            "street": "676 North LaSalle Drive, Suite 400",
            "city": "Chicago",
            "state": "IL",
            "postal_code": "60654",
        },
        "home_address": {
            "street": "2044 North Hoyne Avenue",
            "city": "Chicago",
            "state": "IL",
            "postal_code": "60647",
        },
    },
]
