#!/usr/bin/env bash
# Build the site and publish it to S3 behind CloudFront.
#
# Also completes the loop Terraform cannot close on its own: once CloudFront
# exists, its address has to be registered with Cognito as a permitted sign-in
# redirect. That is passed back into Terraform here rather than being wired
# directly, which would create a dependency cycle (see terraform/data.tf).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# Only fall back to the shared profile when the environment has no credentials
# of its own; that profile is not configured on every machine.
[[ -n "${AWS_ACCESS_KEY_ID:-}" ]] || export AWS_PROFILE="${AWS_PROFILE:-solint-standard}"

cd "$ROOT/terraform"
SITE_URL="$(terraform output -raw site_url)"
BUCKET="$(terraform output -raw web_bucket)"
DISTRIBUTION="$(terraform output -raw cloudfront_distribution_id)"
API_BASE="$(terraform output -raw mock_api_base_url)"
COGNITO_DOMAIN="$(terraform output -raw cognito_hosted_ui_domain)"
CLIENT_ID="$(terraform output -raw cognito_client_id)"
TARGET_NAME="$(terraform console -no-color <<<"var.mcp_target_name" | tr -d '"')"

echo "==> Registering ${SITE_URL} with Cognito as a sign-in redirect"
# Persisted so later plain `terraform apply` runs keep the value instead of
# reverting it. Regenerated automatically, so a new account picks up its own.
cat > "$ROOT/terraform/deployed.auto.tfvars" <<EOF
# Generated by scripts/deploy-web.sh - do not edit by hand.
deployed_web_origin = "${SITE_URL}"
EOF
terraform apply -auto-approve -no-color >/dev/null

echo "==> Building the browser application for ${SITE_URL}"
cd "$ROOT/web"
cat > .env.production <<EOF
# Generated by scripts/deploy-web.sh - do not edit by hand.
VITE_COGNITO_DOMAIN=$COGNITO_DOMAIN
VITE_COGNITO_CLIENT_ID=$CLIENT_ID
VITE_REDIRECT_URI=$SITE_URL/callback
EOF
npm run build --silent

echo "==> Building the API documentation"
uv run --quiet --with pyyaml "$ROOT/scripts/build-docs.py" \
  --spec "$ROOT/mock-api/spec/openapi.yaml.tftpl" \
  --base-url "$API_BASE" \
  --target "$TARGET_NAME" \
  --out "$ROOT/web/dist/docs.html"

echo "==> Uploading to s3://${BUCKET}"
# Fingerprinted assets can be cached hard; the entry points must not be, or
# browsers keep serving an old build after a deploy.
aws s3 sync "$ROOT/web/dist/" "s3://${BUCKET}/" --delete \
  --exclude "index.html" --exclude "docs.html" \
  --cache-control "public,max-age=31536000,immutable" --only-show-errors

aws s3 cp "$ROOT/web/dist/index.html" "s3://${BUCKET}/index.html" \
  --cache-control "no-cache" --content-type "text/html" --only-show-errors

aws s3 cp "$ROOT/web/dist/docs.html" "s3://${BUCKET}/docs.html" \
  --cache-control "no-cache" --content-type "text/html" --only-show-errors

echo "==> Invalidating the CloudFront cache"
aws cloudfront create-invalidation --distribution-id "$DISTRIBUTION" \
  --paths "/*" --query 'Invalidation.Id' --output text

echo
echo "Site: ${SITE_URL}"
echo "Docs: ${SITE_URL}/docs.html"
