#!/usr/bin/env bash
# Write web/.env.local from the deployed stack's Terraform outputs.
#
# Keeps the browser app free of hardcoded ids, so the same source works against
# a stack deployed into any account.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# Only fall back to the shared profile when the environment has no credentials
# of its own; that profile is not configured on every machine.
[[ -n "${AWS_ACCESS_KEY_ID:-}" ]] || export AWS_PROFILE="${AWS_PROFILE:-solint-standard}"

cd "$ROOT/terraform"
DOMAIN="$(terraform output -raw cognito_hosted_ui_domain)"
CLIENT_ID="$(terraform output -raw cognito_client_id)"
GATEWAY="$(terraform output -raw acgw_api_url)"
LOCAL_ORIGIN="$(terraform console -no-color <<<"var.local_web_origin" | tr -d '"')"

cat > "$ROOT/web/.env.local" <<EOF
# Generated by scripts/write-web-config.sh - do not edit by hand.
VITE_COGNITO_DOMAIN=$DOMAIN
VITE_COGNITO_CLIENT_ID=$CLIENT_ID
VITE_REDIRECT_URI=$LOCAL_ORIGIN/callback
VITE_AGENT_GATEWAY_URL=$GATEWAY
EOF

echo "Wrote web/.env.local:"
sed 's/^/  /' "$ROOT/web/.env.local"
